Setup homepage file, style and test
jihaneH/ManiProject pull request #1
Opened 2021-11-29 12:49 UTC by jihaneH

2021-11-29 12:50 UTC, jihaneH reviewed
🛑 Make linter please 🛑

2021-11-29 12:54 UTC, jihaneH reviewed
Please fix the linters
🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 
<img width="569" alt="Capture d’écran 2021-11-29 à 14 01 33" src="https://user-images.githubusercontent.com/7243132/143871759-9ed3a859-141a-4884-b7bb-d56c3497b5a4.png">

2021-11-29 13:06 UTC, jihaneH reviewed
Good job ! 👍 👋

2021-11-29 13:06 UTC, jihaneH commented on .github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
Just a comment for test

2021-11-29 13:06 UTC, jihaneH commented on .hintrc
> +    "no-inline-styles:error"
Just a test

2021-11-29 13:06 UTC, jihaneH commented on .github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
ok

2021-11-29 13:06 UTC, jihaneH commented on .hintrc
> +    "no-inline-styles:error"
no problem

2021-11-29 13:15 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @jihaneH, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] To keep your repo professional, your Pull Request should always have a small description of the changes made in that branch, for instance, you could say that this branch was created to provide feedback on a past project made by you.
- [ ] According to the requirements, this is how you should communicate in a code review:

![image](https://user-images.githubusercontent.com/66967274/143874256-e5f1d675-1d65-454e-89f1-112110ac60d9.png)
- [ ] Keep in mind that your comments should actually have an improvement suggestion, shouldn't be only a test. According to the requirements, you should make at least 2 comments in your review.


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 15:51 UTC, jihaneH commented on css/style.css
> +}
Please compare your design and the template design and try to have marge and width to match the template

2021-11-29 16:43 UTC, jihaneH reviewed
Good job! 👍 👏 👏
There is some issue doesn't been addressed yet.

2021-11-29 16:43 UTC, jihaneH commented on index.html
> +      <h1>Hey We are Mani & Jihane</h1>
Please compare your design and the template design and try to have text align to match the template

Your work :
<img width="234" alt="Capture d’écran 2021-11-29 à 17 37 45" src="https://user-images.githubusercontent.com/7243132/143905961-ae1485fc-2edf-49e1-895a-e98ff0b062ba.png">

The template :
<img width="434" alt="Capture d’écran 2021-11-29 à 17 39 08" src="https://user-images.githubusercontent.com/7243132/143906908-a657f1db-27f7-46b7-9d69-9a452390e619.png">

2021-11-29 17:01 UTC, andersonlebon approved these changes
Hi @jihaneH 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-29 17:32 UTC, merged

2022-01-28 20:47 UTC, jihaneH commented
![icegif-1433](https://user-images.githubusercontent.com/7243132/151619226-0ec14874-a056-456d-86f7-acf8aaf0c3e0.gif)